### ISSUE TITLE
Support for `type = "vim/input"`

### ISSUE THREAD

**Issue by ej-shafran** [notomo/cmdbuf.nvim#10]
From the docs, it seems that `vim.fn.input()` should be supported, however, this following configuration doesn't work as expected:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"folke/tokyonight.nvim",
	"notomo/cmdbuf.nvim",
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- additional
vim.opt.termguicolors = true
vim.cmd([[colorscheme tokyonight]])

vim.keymap.set("c", "<C-f>", function()
	local cmdbuf = require("cmdbuf")

	local cmdtype = vim.fn.getcmdtype()

	cmdbuf.split_open(vim.o.cmdwinheight, {
		line = vim.fn.getcmdline(),
		column = vim.fn.getcmdpos(),
		type = cmdtype == "@" and "vim/input" or "vim/cmd",
	})
	vim.api.nvim_feedkeys(vim.keycode("<C-c>"), "n", true)
end)
```

(You can run this by copying it into `repro.lua` and the running `nvim -u repro.lua`)

If you use this config and run:

1. `:echo input("How are you today? ")`
2. Use `<C-f>` to enter the command buffer
3. Type any response and press `<CR>`

You won't see the thing you wrote being printed out...

**Comment by notomo** [comment]
Thanks for reporting!

Unfortunately, vim/input is not supported execute().
Because normal window cannot continue scripts after input().

I added notomo/cmdbuf.nvim@04076b5 .

**Comment by ej-shafran** [comment]
Would you mind if I tried to get it to work on my own, and opened a pull request if I managed?
