### ISSUE TITLE
Set `cmdwintype` or some other alternative

### ISSUE THREAD

**Issue by ej-shafran** [notomo/cmdbuf.nvim#11]
As suggested in the README, one of the most useful things this plugin provides is the ability to filter out the lines of the command window. However, right now you cannot tell which _type_ of command window is open. I want to, for example, filter out the `:q` and `:wq` commands in a `"vim/cmd"` window, but filter out something else entirely in a `"lua/cmd"` window.

It would be nice to add a feature for this; some sort of argument to the autocmd, perhaps, or a buffer-local variable...

**Comment by notomo** [comment]
Thanks!

Added get_context().type.
