### ISSUE TITLE
feature request: reload respective mode's history on open

### ISSUE THREAD

**Issue by edementyev** [notomo/cmdbuf.nvim#3]
Hi and thanks for the awesome plugin!
Would you be interested in adding such thing? I could (at least try to) provide a PR if the answer would be yes :)

**Comment by notomo** [comment]
Hi!

Does the following setting resolve the issue?

```lua
vim.api.nvim_create_autocmd({ "User" }, {
  group = "cmdbuf_setting",
  pattern = { "CmdbufNew" },
  callback = function()
    vim.bo.bufhidden = "wipe"
  end,
})
```
(or needs `User CmdbufOpen` autocmd?)

If not, could you be more specific?

**Comment by edementyev** [comment]
Yes, this works perfect! Thank you!
Maybe it is worth mentioning in readme, what do you think?

**Comment by notomo** [comment]
> Maybe it is worth mentioning in readme, what do you think?

Good!
I added it. notomo/cmdbuf.nvim@4866c36
Thanks for your reporting!
