### ISSUE TITLE
Feature request: return back to the commad mode with given line

### ISSUE THREAD

**Issue by pecheny** [notomo/cmdbuf.nvim#9]
Hi. Thanks, it appears exactly i was looking for!
Is there an easy way to add C-c feature from the original command-line window? It returns back to the command mode with line under the cursor inserted.
Very handy to preview :s regex replacing result.

**Comment by notomo** [comment]
Thanks!

> Very handy to preview :s regex replacing result.

This seems to be useful.

**Comment by pecheny** [comment]
Wow, great! Thank you!
